const Routes = {
	LOADING: "LOADING",

	LOGIN_STACK: "LOGIN_STACK",
	LOGIN_SCREEN: "LOGIN_SCREEN",

	MAIN_APP: "MAIN_APP",
	HOME_SCREEN: "HOME_SCREEN",

	HOME: "HOME",
	PROFILE: "PROFILE",
};

export default Routes;
